-- MySQL Script generated by MySQL Workbench
-- Thu Nov 17 17:00:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profile` (
  `ID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `like` VARCHAR(45) NULL,
  `subscribers` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`community`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`community` (
  `ID` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `admin_id` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`create`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`create` (
  `ID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `download` VARCHAR(45) NULL,
  `popular` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_users` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `Profile_ID` INT NOT NULL,
  `create_ID` INT NOT NULL,
  PRIMARY KEY (`id_users`, `Profile_ID`),
  INDEX `fk_users_Profile1_idx` (`Profile_ID` ASC) VISIBLE,
  INDEX `fk_users_create1_idx` (`create_ID` ASC) VISIBLE,
  CONSTRAINT `fk_users_Profile1`
    FOREIGN KEY (`Profile_ID`)
    REFERENCES `mydb`.`Profile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_create1`
    FOREIGN KEY (`create_ID`)
    REFERENCES `mydb`.`create` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `ID` INT NOT NULL,
  `categor` VARCHAR(45) NULL,
  `community_ID` INT NOT NULL,
  `Users_ID` INT NOT NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`ID`, `community_ID`, `users_id_users`),
  INDEX `fk_categoria_community1_idx` (`community_ID` ASC) VISIBLE,
  INDEX `fk_categoria_users1_idx` (`users_id_users` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_community1`
    FOREIGN KEY (`community_ID`)
    REFERENCES `mydb`.`community` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `mydb`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
